// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package domain

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type Connection interface {
	IsConnection()
}

type Edge interface {
	IsEdge()
}

type Node interface {
	IsNode()
}

type CreateTaskInput struct {
	Title     string  `json:"title"`
	UserID    string  `json:"userId"`
	Notes     *string `json:"notes"`
	Completed *bool   `json:"completed"`
	Due       string  `json:"due"`
}

type CreateUserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type DeleteTaskInput struct {
	ID string `json:"id"`
}

type DeleteUserInput struct {
	ID string `json:"id"`
}

type PageInfo struct {
	EndCursor   string `json:"endCursor"`
	HasNextPage bool   `json:"hasNextPage"`
}

type PaginationInput struct {
	First *int    `json:"first"`
	After *string `json:"after"`
}

type TaskConnection struct {
	PageInfo *PageInfo   `json:"pageInfo"`
	Edges    []*TaskEdge `json:"edges"`
}

func (TaskConnection) IsConnection() {}

type TaskEdge struct {
	Cursor string `json:"cursor"`
	Node   *Task  `json:"node"`
}

func (TaskEdge) IsEdge() {}

type TasksInput struct {
	Completed *bool `json:"completed"`
}

type UpdateTaskInput struct {
	ID        string     `json:"id"`
	Title     *string    `json:"title"`
	Notes     *string    `json:"notes"`
	Completed *bool      `json:"completed"`
	Due       *time.Time `json:"due"`
}

type UpdateUserInput struct {
	ID    string  `json:"id"`
	Name  *string `json:"name"`
	Email *string `json:"email"`
}

type UserConnection struct {
	PageInfo *PageInfo   `json:"pageInfo"`
	Edges    []*UserEdge `json:"edges"`
}

func (UserConnection) IsConnection() {}

type UserEdge struct {
	Cursor string `json:"cursor"`
	Node   *User  `json:"node"`
}

func (UserEdge) IsEdge() {}

type TaskOrderFields string

const (
	TaskOrderFieldsLatest TaskOrderFields = "LATEST"
	TaskOrderFieldsDue    TaskOrderFields = "DUE"
)

var AllTaskOrderFields = []TaskOrderFields{
	TaskOrderFieldsLatest,
	TaskOrderFieldsDue,
}

func (e TaskOrderFields) IsValid() bool {
	switch e {
	case TaskOrderFieldsLatest, TaskOrderFieldsDue:
		return true
	}
	return false
}

func (e TaskOrderFields) String() string {
	return string(e)
}

func (e *TaskOrderFields) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskOrderFields(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskOrderFields", str)
	}
	return nil
}

func (e TaskOrderFields) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type UserOrderFields string

const (
	UserOrderFieldsLatest UserOrderFields = "LATEST"
	UserOrderFieldsName   UserOrderFields = "NAME"
)

var AllUserOrderFields = []UserOrderFields{
	UserOrderFieldsLatest,
	UserOrderFieldsName,
}

func (e UserOrderFields) IsValid() bool {
	switch e {
	case UserOrderFieldsLatest, UserOrderFieldsName:
		return true
	}
	return false
}

func (e UserOrderFields) String() string {
	return string(e)
}

func (e *UserOrderFields) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserOrderFields(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserOrderFields", str)
	}
	return nil
}

func (e UserOrderFields) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
